paths:
  metadata_path: '<path_to_well_metadata_parquet_file>'
  embeddings_path: '<path_to_well_embeddings_npy_file>'
  exp_folder: "<path_to_experiment_folder>"
  exp_name: "<experiment_name>"
  selected_plates: "./config/balanced_plates.json"

methods:
  - apply_inverse_normal_transform
  - apply_rescale
  - apply_spherizing_transform
  - apply_robust_Z_score
  - apply_median_polish

max_combinations: 100000
n_methods_max: 2 # Should not be higther than n_methods
# If not specified or all, the whole JUMP will be used


#selected_plates: 
#  - EC000010
#  - GR00004379
#  - A1170386

selected_plates: "all" 
# Or balance_selection, a balanced selection to test all normalisations in raisonable
# time and computing resources